[package]
name = "xmr-verification"
version = "0.9.0"
authors = [
    "Piotr Włodarek <contact@eqertoip.com>"
]
license = "MIT"
include = ["LICENSE-MIT"]

[dependencies]
uint = "0.5.0"
lazy_static = "*"

[dev-dependencies]
hex = "0.3.2"
rand = "0.4.3"
time = "*"
